// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhPHTfPAvcBn5t4l-kkvVbBBTHIMgnaOQ',
    appId: '1:771830925506:web:19b3ac595dcfb88f70935b',
    messagingSenderId: '771830925506',
    projectId: 'test-f17c2',
    authDomain: 'test-f17c2.firebaseapp.com',
    storageBucket: 'test-f17c2.appspot.com',
    measurementId: 'G-4DDPYQ2E4F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHXSJRktzPXgYcxPT-wwo82_4nguykswU',
    appId: '1:771830925506:android:ec4707703cbfb28870935b',
    messagingSenderId: '771830925506',
    projectId: 'test-f17c2',
    storageBucket: 'test-f17c2.appspot.com',
  );
}
